# Data Preprocessing for Recommender System

## Objective
This notebook prepares the dataset for model training and evaluation.

We will:
- Clean and validate raw interactions
- Transform ratings into implicit feedback (if needed)
- Filter sparse users and items
- Prepare data for chronological splitting
- Export clean interaction data

Important: No statistical learning or feature engineering that uses global data will be performed here to avoid data leakage.

## Imports and Configuration

In [1]:
import pandas as pd

In [10]:
class Dataset():
    def __init__(self, path):
        self.path = path
        self.dataset = pd.read_csv(self.path)

## Load Raw Dataset

Load the raw interactions dataset.

In [11]:
rating_dataset = Dataset("../data/raw/ml-latest-small/ratings.csv")

In [13]:
rating_dataset.dataset.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [14]:
rating_dataset.dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

## Initial Data Inspection

We inspect:
- Missing values
- Duplicates
- Basic statistics
- Unique users/items

In [23]:
print("Null Values:", end="\n")
print(rating_dataset.dataset.isnull().sum())
print("Duplicate Values:", rating_dataset.dataset.duplicated().sum())

print("Unique users:", rating_dataset.dataset["userId"].nunique())
print("Unique items:", rating_dataset.dataset["movieId"].nunique())
print("Total interactions:", len(rating_dataset.dataset))

Null Values:
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64
Duplicate Values: 0
Unique users: 610
Unique items: 9724
Total interactions: 100836

## Data Cleaning

- Ensure correct data types

In [25]:
rating_dataset.dataset["timestamp"] = pd.to_datetime(rating_dataset.dataset["timestamp"], unit="s")
rating_dataset.dataset.head()

   userId  movieId  rating           timestamp
0       1        1     4.0 2000-07-30 18:45:03
1       1        3     4.0 2000-07-30 18:20:47
2       1        6     4.0 2000-07-30 18:37:04
3       1       47     5.0 2000-07-30 19:03:35
4       1       50     5.0 2000-07-30 18:48:51